name: Deploy to Github Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.job
        uses: actions/setup-node@v3
        with:
          version: "18"

      - name: Install Dependencies
        run: npm i

      - name: Build Project
        run: npm run build

      - name: Prepare Deployment Folder
        run: |
          mkdir deploy
          #Copy only public files/folders (not src/not dev files)
          cp -r index.html index.css favicon.ico assets public style deploy/ || true
          #Copy dist
          cp -r dist deploy/dist

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./deploy
